name: Deploy to AWS EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Optional: หากต้องการ build และทดสอบ image ใน CI ก่อน deploy
      - name: Build Docker images
        run: docker-compose build

      # Deploy to AWS EC2 via SSH
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd $EC2_PROJECT_PATH
            # ดึง code ล่าสุด (ในกรณีที่ใช้ git pull บน EC2)
            git pull origin main
            # ปิด container เก่า
            docker-compose down
            # Build/Run container ใหม่ (หรือใช้ docker-compose pull หาก images อยู่ใน registry)
            docker-compose up -d
        env:
          EC2_PROJECT_PATH: ${{ secrets.EC2_PROJECT_PATH }}
